module NonlinearEMKGDoubleNull

include("Coordinates.jl")
include("Fields.jl")
include("EinsteinSector.jl")
include("StressEnergy.jl")
include("NonlinearEMKG.jl")
include("AdaptiveMRT.jl")
include("StewartAMR.jl")
include("InitialData.jl")
include("Evolution.jl")
include("Diagnostics.jl")
include("FixedBackgroundAdaptive.jl")

export RNParams, EvolutionParams, Grid, State
export compact_mrt_grid, ef_v_mrt_grid, ef_uv_mrt_grid, initialize_state
export initialize_gp2025_bump_state, gaussian_envelope, gp2025_bump_envelope
export evolve!, maxwell_residuals
export MetricState, einstein_backreaction_rhs!
export NLState, initialize_nonlinear_state, evolve_nonlinear!, mrt2013_background_f
export mrt2013_grid, mrt2013_areal_radius, mrt2013_metric_f, initialize_mrt2013_uncharged_ingoing!
export gp2026_grid
export initialize_mrt2013_outgoing_wave!, mrt2013_initial_bondi_mass, mrt2013_degenerate_horizon_f0
export initialize_mrt2013_charged_outgoing_wave!
export gp2026_single_pulse_envelope, gp2026_extremal_gauge_initial_radius
export gp2026_extremal_gauge_ru, gp2026_extremal_gauge_rv, gp2026_fcorner_code
export gp2026_initial_scalar_data
export initialize_gp2026_single_pulse!
export gp2026_exact_extremal_rn_radius, gp2026_exact_extremal_rn_fcode
export initialize_gp2026_exact_extremal_rn!
export mrt2013_initial_rv_profile
export charged_scalar_rhs, charged_reduced_scalar_rhs, charged_reduced_charge_rhs
export metric_rhs, maxwell_rhs
export NLSlice, NLPoint, AdaptiveNLState, PointSplittingConfig, HorizonChoppingConfig
export HorizonRefinementConfig, slice_point
export slice_from_rectangular, adaptive_state_from_rectangular, west_boundary_from_rectangular
export NLRow, UAdaptiveNLState, ThroatRowDiagnostics
export ThroatMatchCandidate, ThroatMatchBand, RhoLapseDiagnostics, ThroatBoundarySample
export row_from_rectangular, adaptive_state_from_u_rows
export throat_row_diagnostics, throat_matching_candidate, throat_matching_band
export rho_lapse_diagnostics, throat_boundary_sample, throat_boundary_series, range_width
export throat_row_du, eta_row_du, geometric_row_du, gp2026_row_step_du
export realized_row_change_summary
export row_lte_error, buffered_flag_intervals, row_lte_patches
export berger_oliger_row_lte
export row_point, interpolate_row, refined_v_patch_grid
export inject_row_patch, reintegrate_row_suffix, berger_oliger_refine_patch
export advance_u_row_berger_oliger
export StewartAMRConfig, StewartAMRStats, StewartAMRLevel, StewartAMRHierarchy
export initialize_stewart_hierarchy, advance_stewart_hierarchy!
export stewart_hierarchy_depth, stewart_hierarchy_intervals
export validate_stewart_hierarchy, interpolate_parent_boundary
export StewartRootStepController, deepest_recent_lte, next_stewart_root_du
export interpolate_slice, refine_u_grid, refine_slice, truncate_slice
export refine_slice_constrained
export spacing_refinement_flags, variation_refinement_flags, point_splitting_flags
export adaptive_outgoing_expansion, chop_inside_apparent_horizon
export horizon_refinement_flags, refine_near_apparent_horizon
export advance_adaptive_slice, evolve_adaptive
export gp2026_na_boundary_point, advance_u_row, evolve_gp2026_u_adaptive
export StressEnergyComponents, stress_energy, stress_energy_reduced_scalar
export covariant_scalar_derivatives, current_components
export outgoing_constraint_source, ingoing_constraint_source
export horizon_phi_series, fit_power_law
export renormalized_hawking_mass, renormalized_hawking_mass_profile, bondi_mass_profile
export uncharged_mass_flux_u_profile
export uncharged_flux_integrated_mass_profile
export charged_charge_flux_u_profile, charged_charge_flux_v_profile
export charged_flux_integrated_charge_profile
export charged_mass_flux_u_profile, charged_flux_integrated_mass_profile
export outgoing_expansion_profile, apparent_horizon_location
export TrappedSurfaceSample, VTrapDiagnostic, HorizonChargeDensitySample
export row_outgoing_expansion, row_expansion_minimum, row_apparent_horizon_crossing
export vtrap_diagnostic, refined_vtrap_sample, trapped_surface_invariants
export row_horizon_charge_density_sample, apparent_horizon_charge_density_series
export gp2026_rphi_profile, gp2026_horizon_rphi_series
export ThroatBoundaryObservables, throat_boundary_observables
export cell_equation_residual_summary
export gp2026_initial_constraint_residuals
export horizon_charge_density_series, horizon_energy_density_series
export horizon_energy_density_divided_series, horizon_energy_density_direct_series
export horizon_energy_density_divided_components
export horizon_charge_density_extrapolated_series
export horizon_energy_density_extrapolated_series
export horizon_energy_density_extrapolated_components
export conformal_weight_s
export FixedBackgroundVRefinementConfig, FixedBackgroundVRefinementSummary
export FixedBackgroundPatchResult
export fixed_background_v_refinement_indicators, fixed_background_v_refinement_flags
export refine_fixed_background_v_grid, evolve_fixed_background_v_adaptive
export fixed_background_patch_indices, evolve_fixed_background_v_patch
export fixed_background_patch_parent_errors
export rstar, areal_radius, metric_F, metric_f, metric_ftilde, radius_from_rstar, compact_v_from_ef_v, compact_u_from_ef_u

end
